"""Compile the original local lunar illustration to a small firmware luminance table.

Pillow is used only for this offline source-asset conversion, not firmware or CI.
"""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
source = root / 'design/home-tactical-2026-09-28/lunar-texture-source.png'
with Image.open(source) as image:
    gray = image.convert('L')
    # The source disk spans roughly 94% of the image. Resample its albedo into
    # a64x64 table; the runtime still computes the circular/phase boundary.
    size = gray.width
    margin = round(size * .03)
    values = list(gray.crop((margin, margin, size-margin, size-margin)).resize((64,64),Image.Resampling.LANCZOS).getdata())
target = root / 'src/gui/mainbar/main_tile/home_moon_texture.h'
rows = [', '.join(map(str,values[y*64:(y+1)*64])) for y in range(64)]
target.write_text('// Original ImageGen lunar albedo; generated by support/generate_home_moon_texture.py.\n'
                  '// Illustration only. Runtime phase and illumination remain computed.\n'
                  'static const uint8_t home_moon_albedo[4096] = {\n    '+',\n    '.join(rows)+'\n};\n')
