name=HynTouch
version=1.0.0
author=LilyGo
maintainer=LilyGo
sentence=Bundled LilyGo Hynitron touch driver for T-Deck Pro.
paragraph=Local copy from LilyGo T-Deck Pro V2 example firmware.
category=Device Control
url=https://github.com/Xinyuan-LilyGO/T-Deck-Pro
architectures=esp32
